workflows:
  android-workflow:
    name: Android workflow
    instance_type: linux  # доступный на бесплатном плане
    environment:
      vars:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # убедись, что секрет задан в Codemagic
      flutter: stable
      android: true
      jdk: openjdk-11  # поддерживаемая версия для сборки
    scripts:
      - name: Get dependencies
        script: |
          cd android_app
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
