workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    instance_type: standard
    environment:
      vars:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      flutter: none
      xcode: none
    scripts:
      - name: Checkout code
        script: |
          git clone https://github.com/${GITHUB_USERNAME}/Shwedtreid.git .
      - name: Build APK
        script: |
          cd android_app
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify_on_build_fail: true
        notify_on_build_success: true
