workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    max_build_duration: 60
    environment:
      vars: {}  # пустой словарь вместо 'none'
    scripts:
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
