workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    environment:
      vars:
        GITHUB_USERNAME: bearzunlimited17-hash
        GITHUB_REPO: Shwedtreid
        GITHUB_PAT: $GITHUB_PAT  # Лучше хранить как secure environment variable
    scripts:
      - echo "Сборка проекта..."
      - cd android_app
      - ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/**/*.apk
    publishing:
      github:
        enabled: false  # если нужно пушить APK в релиз — можно добавить позже
