workflows:
  android-workflow:
    name: Android APK Build
    instance_type: linux
    max_build_duration: 60
    environment:
      java: openjdk-17
      vars:
        # обычные переменные, например имя приложения
        APP_NAME: "Shwedtreid"
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Get dependencies
        script: ./gradlew build
      - name: Build Release APK
        script: ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/**/*.apk
