workflows:
  android-workflow:
    name: Build Android APK
    instance_type: linux  # только linux разрешен на бесплатном плане
    scripts:
      - name: Build APK
        script: |
          cd android_app
          ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/**/*.apk
