workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      android: true
      java: openjdk11
    scripts:
      - name: Install backend dependencies
        script: |
          cd backend
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file, skipping"

      - name: Install Android dependencies
        script: |
          cd android_app
          ./gradlew clean
          ./gradlew dependencies

      - name: Build APK
        script: |
          cd android_app
          ./gradlew assembleRelease

    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk

    publishing:
      email:
        recipients:
          - your_email@example.com
