workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    scripts:
      - name: Build Android APK
        script: |
          cd android_app
          ./gradlew clean assembleRelease
      - name: Install backend dependencies
        script: |
          pip install --upgrade pip
          pip install -r ../backend/requirements.txt
    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk
