workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    max_build_duration: 60
    environment:
      vars:
        # Не ставим пустые значения! Если нужны секреты, храни их через UI Codemagic
        # Пример: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      android: true
      jdk: openjdk-17
    scripts:
      - name: Install dependencies
        script: |
          echo "Устанавливаем зависимости проекта"
          ./gradlew dependencies || echo "Gradle wrapper не найден"
      - name: Build APK
        script: |
          echo "Сборка APK"
          ./gradlew assembleRelease || exit 1
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        # Убираем notify_on_build_fail и notify_on_build_success, они не разрешены
        recipients:
          - your-email@example.com
