workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        # Здесь можно указать переменные окружения для проекта, например:
        # BTC_API_KEY: $BTC_API_KEY
    scripts:
      - name: Build Android APK
        script: |
          echo "Сборка APK..."
          cd android_app
          ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk
