workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux        # Бесплатный план Linux
    environment:
      vars:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Обязательно добавь секрет в Codemagic
      flutter: stable          # Flutter SDK для сборки, если нужен
    scripts:
      - name: Clean Project
        script: |
          cd android_app
          if [ -f ./gradlew ]; then
            ./gradlew clean
          else
            echo "gradlew не найден, попробуй gradle wrapper"
            gradle wrapper
          fi
      - name: Build APK
        script: |
          cd android_app
          ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
