workflows:
  android-workflow:
    name: Android workflow
    instance_type: linux  # Бесплатный план поддерживает только linux
    max_build_duration: 60
    environment:
      vars:
        GITHUB_TOKEN: $GITHUB_PAT
    scripts:
      - name: Checkout repository
        script: |
          git clone https://bearzunlimited17-hash:$GITHUB_PAT@github.com/bearzunlimited17-hash/Shwedtreid.git .
      - name: Build Android APK
        script: |
          echo "Starting Gradle build..."
          ./gradlew assembleRelease || ./gradlew build
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients: ["youremail@example.com"]
