workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    environment:
      vars:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      flutter: stable
      xcode: null
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing backend dependencies..."
          # Пример: pip install -r requirements.txt, если нужно
      - name: Build Android APK
        script: |
          echo "Building APK..."
          cd android_app
          ./gradlew assembleRelease
    artifacts:
      - android_app/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients: []
