workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux  # бесплатно доступный инстанс
    max_build_duration: 60
    environment:
      vars:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # корректный формат переменной
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          echo "Устанавливаем зависимости"
          flutter pub get
      - name: Build APK
        script: |
          echo "Собираем релизный APK"
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
