workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux  # Бесплатный план
    max_build_duration: 60

    environment:
      vars:
        GITHUB_TOKEN: $GITHUB_TOKEN  # Если нужен токен, он должен быть строкой
      flutter: stable

    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
