workflows:
  android-workflow:
    name: Android Free Plan
    instance_type: linux      # Бесплатный план поддерживает только 'linux' или 'windows_x2'
    environment:
      vars:
        GITHUB_USERNAME: bearzunlimited17-hash
        GITHUB_REPO: Shwedtreid
        GITHUB_PAT: $GITHUB_PAT  # Настрой секрет на Codemagic
    scripts:
      - name: Checkout project
        script: git checkout main
      - name: Install dependencies
        script: ./gradlew dependencies
      - name: Assemble Release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients: ["your-email@example.com"]  # сюда можно свой email
